var fruit = new Object('Apple');
var place = new Object('shimogha');
var vehicle = new Object('Royal Enfield');
var people = new Object('Passengers');
var man = new Object('leg');
console.log('value', fruit);
console.log('value', place);
console.log('value', vehicle);
console.log('value', people);
console.log('value', man);